(function() {
    // --- INTERNAL STATE ---
    let isSongMakerPlaying = false;
    let isSongMakerRepeatOn = false;
    let songMakerPlaybackTimeouts = [];
    
    // --- DEPENDENCIES (Injected via init) ---
    let deps = {
        initAudioContext: () => false,
        playNote: () => {},
        stopAudioForNote: () => {},
        getFullScaleRange: () => [],
        getKeysData: () => [],
        getEffectiveBaseTempoMs: () => 750,
        syncTempo: () => {},
        globalActiveMidiNotes: new Set(),
        updateSheetMusicHighlight: () => {}
    };

    // --- CORE PLAYBACK CONTROLS ---

    function stopSongMaker(resetButtonUI = true) {
        isSongMakerPlaying = false;
        songMakerPlaybackTimeouts.forEach(clearTimeout);
        songMakerPlaybackTimeouts = [];
        document.querySelectorAll('.key.auto-playing-note').forEach(k => k.classList.remove('auto-playing-note'));
        
        // Immediately halt any actively playing sequence audio generated by the Song Maker
        deps.globalActiveMidiNotes.forEach(midi => deps.stopAudioForNote(midi));
        deps.globalActiveMidiNotes.clear();
        deps.updateSheetMusicHighlight();

        if (resetButtonUI) {
            const playBtn = document.getElementById('songMakerPlayBtn');
            if (playBtn) {
                playBtn.textContent = 'Play Song';
                playBtn.classList.remove('playing');
            }
        }
        
        const autoPlayBtn = document.getElementById('autoPlayBtn');
        if (autoPlayBtn) autoPlayBtn.disabled = false;
    }

    function toggleSongMaker() {
        if (!deps.initAudioContext()) return;
        if (isSongMakerPlaying) {
            stopSongMaker();
        } else {
            // Stop AutoPlay if it's currently running
            if (window.AutoPlaySystem && window.AutoPlaySystem.isPlaying()) {
                window.AutoPlaySystem.stop(true);
            }
            playSongMaker();
        }
    }

    function playSongMaker() {
        const tracksContainer = document.getElementById('songMakerTracksContainer');
        let trackDivs = Array.from(tracksContainer.querySelectorAll('.song-maker-track'));
        const playBtn = document.getElementById('songMakerPlayBtn');
        const mainRootPitchClass = document.getElementById('rootNoteSelect').value;
        const semisteps = document.getElementById('semistepsInput').value;
        
        const scalePalette = deps.getFullScaleRange(mainRootPitchClass, semisteps);

        if (scalePalette.length === 0) {
            alert("The current scale is empty. Cannot play song.");
            return;
        }

        const mainRootNote = scalePalette.find(n => n.pitchClass === mainRootPitchClass && n.octave === 4) ||
                             scalePalette.find(n => n.pitchClass === mainRootPitchClass);

        if (!mainRootNote) {
            alert(`Master root note "${mainRootPitchClass}" not found in the generated scale range.`);
            return;
        }
        const mainRootNoteIndex = scalePalette.indexOf(mainRootNote);

        let trackData = trackDivs.map(div => ({
            startingIntervals: div.querySelector('.track-roots-input').value.split(',').map(s => parseInt(s.trim(), 10)).filter(s => !isNaN(s)),
            intervals: div.querySelector('.track-intervals-input').value.split(',').map(s => s.trim()),
            isMuted: div.querySelector('.track-button.mute').classList.contains('active'),
            isSolo: div.querySelector('.track-button.solo').classList.contains('active'),
            velocity: parseFloat(div.querySelector('.track-velocity-slider').value),
            octaveOffset: parseInt(div.querySelector('.track-octave-input').value, 10) || 0,
            element: div
        }));

        const isAnySolo = trackData.some(t => t.isSolo);
        let activeTracks = isAnySolo ? trackData.filter(t => t.isSolo) : trackData.filter(t => !t.isMuted);

        if (activeTracks.length === 0 && !isSongMakerRepeatOn) {
            alert("No active tracks to play. Un-mute a track or de-activate solo mode.");
            return;
        }

        isSongMakerPlaying = true;
        playBtn.textContent = 'Stop';
        playBtn.classList.add('playing');
        
        const autoPlayBtn = document.getElementById('autoPlayBtn');
        if (autoPlayBtn) autoPlayBtn.disabled = true;
        
        let masterTimeline = [];
        const isHumanizerActive = document.getElementById('humanizerToggleBtn').classList.contains('active');
        const timingVariation = isHumanizerActive ? parseInt(document.getElementById('humanizerTimingSlider').value, 10) : 0;
        const velocityVariation = isHumanizerActive ? parseInt(document.getElementById('humanizerVelocitySlider').value, 10) : 0;
        
        const effectiveBaseTempoMs = deps.getEffectiveBaseTempoMs();
        const keysData = deps.getKeysData();

        activeTracks.forEach(track => {
            let currentTime = 0;

            track.startingIntervals.forEach(startInterval => {
                const startNoteIndex = mainRootNoteIndex + (startInterval - 1);
                const rootNoteData = scalePalette[startNoteIndex];
                
                if (!rootNoteData) {
                     console.warn(`Starting interval "${startInterval}" is out of the scale's range. Skipping.`);
                     return; 
                }
                const rootNoteIndexInPalette = scalePalette.indexOf(rootNoteData);
                let currentNoteEvent = null;

                track.intervals.forEach(intervalStr => {
                    let noteToPlay = null;
                    if(intervalStr === '-') { 
                        if (currentNoteEvent) {
                            currentNoteEvent.duration += effectiveBaseTempoMs; // Effectively ties/holds the previous note
                        }
                    } else {
                        const interval = parseInt(intervalStr, 10);
                        if (!isNaN(interval)) {
                            if (interval !== 0) { 
                                const targetIndex = rootNoteIndexInPalette + (interval - (interval > 0 ? 1 : 0));
                                if (targetIndex >= 0 && targetIndex < scalePalette.length) {
                                    let baseNote = scalePalette[targetIndex];
                                    let targetMidi = baseNote.midi + (track.octaveOffset * 12);
                                    let actualKey = keysData.find(k => k.midi === targetMidi);
                                    
                                    if (actualKey) {
                                        noteToPlay = actualKey;
                                    } else {
                                        // Synthesize properties if out of visual keyboard bounds
                                        noteToPlay = {
                                            midi: Math.max(0, Math.min(127, targetMidi)),
                                            frequency: baseNote.frequency * Math.pow(2, track.octaveOffset),
                                            idSuffix: null
                                        };
                                    }
                                } else {
                                    console.warn(`Interval ${interval} from start interval ${startInterval} is out of range.`);
                                }
                            }
                        }
                    }
                    
                    if (noteToPlay) {
                        let humanizedTime = currentTime;
                        if (isHumanizerActive) {
                            const timeOffset = (effectiveBaseTempoMs * (timingVariation / 100)) * (Math.random() * 2 - 1);
                            humanizedTime += timeOffset;
                        }
                        
                        let humanizedVelocity = track.velocity;
                        if(isHumanizerActive) {
                            const velOffset = Math.floor(velocityVariation * (Math.random() * 2 - 1));
                            humanizedVelocity = Math.max(0, Math.min(1, humanizedVelocity + velOffset / 127));
                        }

                        currentNoteEvent = {
                            time: humanizedTime,
                            note: noteToPlay,
                            velocity: humanizedVelocity,
                            duration: effectiveBaseTempoMs // Default to 1 interval tick
                        };
                        masterTimeline.push(currentNoteEvent);
                    } else if (intervalStr !== '-') {
                        currentNoteEvent = null; // A rest breaks the hold chain
                    }
                    currentTime += effectiveBaseTempoMs;
                });
            });
        });
        
        masterTimeline.sort((a,b) => a.time - b.time);

        masterTimeline.forEach(event => {
            const timeoutId = setTimeout(() => {
                if (!isSongMakerPlaying) return;
                deps.playNote(event.note.frequency, event.velocity, event.note.midi, true);
                deps.globalActiveMidiNotes.add(event.note.midi);
                deps.updateSheetMusicHighlight();

                if (event.note.idSuffix) {
                    const keyElement = document.getElementById('key' + event.note.idSuffix);
                    if (keyElement) {
                        keyElement.classList.add('auto-playing-note');
                    }
                }
                
                // Calculate physical duration for audio cutoff & visuals
                const stopTime = event.duration * 0.95; 
                
                const stopTimeout = setTimeout(() => {
                    if (!isSongMakerPlaying) return; 
                    
                    deps.stopAudioForNote(event.note.midi); // End sequence hold dynamically
                    deps.globalActiveMidiNotes.delete(event.note.midi);
                    deps.updateSheetMusicHighlight();
                    
                    if (event.note.idSuffix) {
                        const keyElement = document.getElementById('key' + event.note.idSuffix);
                        if (keyElement) keyElement.classList.remove('auto-playing-note');
                    }
                }, stopTime);
                songMakerPlaybackTimeouts.push(stopTimeout);

            }, event.time);
            songMakerPlaybackTimeouts.push(timeoutId);
        });
        
        const totalDuration = masterTimeline.length > 0 ? Math.max(...masterTimeline.map(e => e.time + e.duration)) : 
                              (activeTracks.length > 0 ? Math.max(...activeTracks.map(t => (t.startingIntervals.length * t.intervals.length) || 0)) * effectiveBaseTempoMs : effectiveBaseTempoMs);

        const endTimeout = setTimeout(() => {
            if (isSongMakerPlaying) {
                if (isSongMakerRepeatOn) {
                    document.querySelectorAll('.key.auto-playing-note').forEach(k => k.classList.remove('auto-playing-note'));
                    songMakerPlaybackTimeouts = [];
                    deps.globalActiveMidiNotes.clear();
                    deps.updateSheetMusicHighlight();
                    playSongMaker(); // Loop
                } else {
                    stopSongMaker();
                }
            }
        }, totalDuration);
        songMakerPlaybackTimeouts.push(endTimeout);
    }

    // --- UI GENERATION ---

    function generateSongMakerTracks(count) {
        const container = document.getElementById('songMakerTracksContainer');
        container.innerHTML = '';
        for (let i = 1; i <= count; i++) {
            const trackDiv = document.createElement('div');
            trackDiv.className = 'song-maker-track';
            trackDiv.innerHTML = `
                <div class="song-maker-track-header">
                    <span class="track-title">Track ${i}</span>
                    <button class="track-button solo">Solo</button>
                    <button class="track-button mute">Mute</button>
                    <button class="track-button random-track">Random</button>
                    <label>Oct:</label>
                    <input type="number" class="track-octave-input" value="0" min="-4" max="4" style="width: 45px;" title="Octave Offset">
                    <label>Vel:</label>
                    <input type="range" class="track-velocity-slider" min="0" max="1" step="0.01" value="0.7">
                </div>
                <div class="track-inputs">
                    <input type="text" class="track-roots-input" placeholder="Starting Intervals (relative to Root) e.g., 1, 5, -2">
                    <input type="text" class="track-intervals-input" placeholder="Scale Intervals (relative to Start) e.g., 1, 3, 5, 0, -">
                </div>
            `;
            container.appendChild(trackDiv);
        }
        
        container.querySelectorAll('.track-button.solo').forEach(btn => btn.addEventListener('click', () => btn.classList.toggle('active')));
        container.querySelectorAll('.track-button.mute').forEach(btn => btn.addEventListener('click', () => btn.classList.toggle('active')));
        container.querySelectorAll('.track-button.random-track').forEach(btn => btn.addEventListener('click', (e) => randomizeTrack(e.target.closest('.song-maker-track'))));
    }
    
    function randomizeTrack(track) {
        const rootsInput = track.querySelector('.track-roots-input');
        const intervalsInput = track.querySelector('.track-intervals-input');

        const numRoots = Math.floor(Math.random() * 3) + 1; 
        let roots = [];
        for (let i = 0; i < numRoots; i++) {
            roots.push(Math.floor(Math.random() * 15) - 7); 
        }
        rootsInput.value = roots.join(', ');

        const numIntervals = Math.floor(Math.random() * 9) + 8; 
        let intervals = [];
        for (let i = 0; i < numIntervals; i++) {
            const rand = Math.random();
            if (rand < 0.75) { 
                intervals.push(Math.floor(Math.random() * 8) + 1); 
            } else if (rand < 0.9) { 
                intervals.push('0');
            } else { 
                intervals.push('-');
            }
        }
        intervalsInput.value = intervals.join(', ');
    }

    function generateRandomSongData() {
        document.querySelectorAll('.song-maker-track').forEach(randomizeTrack);
    }

    function setupSongMakerControls() {
        const trackCountInput = document.getElementById('songMakerTrackCount');
        if (!trackCountInput) return; // Ensure DOM elements exist

        trackCountInput.addEventListener('change', () => {
            const count = parseInt(trackCountInput.value, 10);
            if (count > 0 && count <= 16) {
                generateSongMakerTracks(count);
            }
        });

        document.getElementById('humanizerToggleBtn').addEventListener('click', (e) => {
            e.target.classList.toggle('active');
            document.getElementById('humanizerControls').classList.toggle('visible');
        });
        
        document.getElementById('saveSongBtn').addEventListener('click', saveSongToFile);
        document.getElementById('loadSongBtn').addEventListener('click', () => document.getElementById('songFileInput').click());
        document.getElementById('songFileInput').addEventListener('change', loadSongFromFile);
        document.getElementById('saveMidiBtn').addEventListener('click', saveToMidiFile);
        document.getElementById('songMakerRandomBtn').addEventListener('click', generateRandomSongData);
        
        document.getElementById('songMakerPlayBtn').addEventListener('click', toggleSongMaker);
        
        const repeatBtn = document.getElementById('songMakerRepeatBtn');
        repeatBtn.addEventListener('click', () => {
            isSongMakerRepeatOn = !isSongMakerRepeatOn;
            repeatBtn.textContent = isSongMakerRepeatOn ? 'Repeat On' : 'Repeat Off';
            repeatBtn.classList.toggle('active', isSongMakerRepeatOn);
        });

        // Initialize default tracks
        generateSongMakerTracks(parseInt(trackCountInput.value, 10)); 
    }

    // --- FILE I/O ---

    function saveSongToFile() {
        const tracks = Array.from(document.querySelectorAll('.song-maker-track')).map(div => ({
            startingIntervals: div.querySelector('.track-roots-input').value,
            intervals: div.querySelector('.track-intervals-input').value,
            isMuted: div.querySelector('.track-button.mute').classList.contains('active'),
            isSolo: div.querySelector('.track-button.solo').classList.contains('active'),
            velocity: div.querySelector('.track-velocity-slider').value,
            octaveOffset: parseInt(div.querySelector('.track-octave-input').value, 10) || 0
        }));

        const humanizer = {
            active: document.getElementById('humanizerToggleBtn').classList.contains('active'),
            timing: document.getElementById('humanizerTimingSlider').value,
            velocity: document.getElementById('humanizerVelocitySlider').value
        };

        const songData = {
            trackCount: tracks.length,
            tracks: tracks,
            humanizer: humanizer,
            tempo: document.getElementById('tempoInput').value,
            repeat: isSongMakerRepeatOn
        };
        
        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(songData, null, 2));
        const downloadAnchorNode = document.createElement('a');
        downloadAnchorNode.setAttribute("href", dataStr);
        downloadAnchorNode.setAttribute("download", "piano_song.json");
        document.body.appendChild(downloadAnchorNode);
        downloadAnchorNode.click();
        downloadAnchorNode.remove();
    }

    function loadSongFromFile(event) {
        const file = event.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = function(e) {
            try {
                const songData = JSON.parse(e.target.result);
                if (!songData || !songData.tracks) throw new Error("Invalid format");
                
                stopSongMaker();
                
                document.getElementById('tempoInput').value = songData.tempo || 80;
                document.getElementById('tempoSlider').value = songData.tempo || 80;
                if (deps.syncTempo) {
                    deps.syncTempo(songData.tempo || 80);
                }

                const trackCountInput = document.getElementById('songMakerTrackCount');
                trackCountInput.value = songData.trackCount;
                generateSongMakerTracks(songData.trackCount);

                const trackDivs = document.querySelectorAll('.song-maker-track');
                songData.tracks.forEach((track, index) => {
                    if (trackDivs[index]) {
                        const div = trackDivs[index];
                        div.querySelector('.track-roots-input').value = track.startingIntervals;
                        div.querySelector('.track-intervals-input').value = track.intervals;
                        div.querySelector('.track-velocity-slider').value = track.velocity;
                        div.querySelector('.track-octave-input').value = track.octaveOffset || 0;
                        div.querySelector('.track-button.mute').classList.toggle('active', track.isMuted);
                        div.querySelector('.track-button.solo').classList.toggle('active', track.isSolo);
                    }
                });

                const humanizerBtn = document.getElementById('humanizerToggleBtn');
                const humanizerControls = document.getElementById('humanizerControls');
                humanizerBtn.classList.toggle('active', songData.humanizer.active);
                humanizerControls.classList.toggle('visible', songData.humanizer.active);
                document.getElementById('humanizerTimingSlider').value = songData.humanizer.timing;
                document.getElementById('humanizerVelocitySlider').value = songData.humanizer.velocity;
                
                const repeatBtn = document.getElementById('songMakerRepeatBtn');
                isSongMakerRepeatOn = songData.repeat || false;
                repeatBtn.textContent = isSongMakerRepeatOn ? 'Repeat On' : 'Repeat Off';
                repeatBtn.classList.toggle('active', isSongMakerRepeatOn);

                alert("Song loaded successfully!");
            } catch (error) {
                alert("Failed to load song file. Error: " + error.message);
            }
        };
        reader.readAsText(file);
        event.target.value = null; 
    }

    // --- MIDI EXPORT ---

    function saveToMidiFile() {
        const mainRootPitchClass = document.getElementById('rootNoteSelect').value;
        const semisteps = document.getElementById('semistepsInput').value;
        const scalePalette = deps.getFullScaleRange(mainRootPitchClass, semisteps);
        const trackDivs = Array.from(document.querySelectorAll('.song-maker-track'));

        const mainRootNote = scalePalette.find(n => n.pitchClass === mainRootPitchClass && n.octave === 4) ||
                             scalePalette.find(n => n.pitchClass === mainRootPitchClass);

        if (!mainRootNote) {
            alert(`Master root note "${mainRootPitchClass}" not found for MIDI export.`);
            return;
        }
        const mainRootNoteIndex = scalePalette.indexOf(mainRootNote);

        let trackData = trackDivs.map((div, i) => ({
            channel: i,
            startingIntervals: div.querySelector('.track-roots-input').value.split(',').map(s => parseInt(s.trim(), 10)).filter(s => !isNaN(s)),
            intervals: div.querySelector('.track-intervals-input').value.split(',').map(s => s.trim()),
            isMuted: div.querySelector('.track-button.mute').classList.contains('active'),
            isSolo: div.querySelector('.track-button.solo').classList.contains('active'),
            baseVelocity: parseFloat(div.querySelector('.track-velocity-slider').value) * 127,
            octaveOffset: parseInt(div.querySelector('.track-octave-input').value, 10) || 0
        }));

        const isAnySolo = trackData.some(t => t.isSolo);
        let activeTracks = isAnySolo ? trackData.filter(t => t.isSolo) : trackData.filter(t => !t.isMuted);
        
        const isHumanizerActive = document.getElementById('humanizerToggleBtn').classList.contains('active');
        const timingVariation = isHumanizerActive ? parseInt(document.getElementById('humanizerTimingSlider').value, 10) : 0;
        const velocityVariation = isHumanizerActive ? parseInt(document.getElementById('humanizerVelocitySlider').value, 10) : 0;

        const ticksPerBeat = 480;
        const beatDurationTicks = ticksPerBeat;

        let midiTracks = [];

        activeTracks.forEach(track => {
            let noteEvents = [];
            let currentTimeTicks = 0;

            track.startingIntervals.forEach(startInterval => {
                const startNoteIndex = mainRootNoteIndex + (startInterval - 1);
                const rootNoteData = scalePalette[startNoteIndex];

                if (!rootNoteData) return; 
                const rootNoteIndexInPalette = scalePalette.indexOf(rootNoteData);

                track.intervals.forEach(intervalStr => {
                    let noteToPlay = null;
                    let isHold = false;
                    
                    if (intervalStr === '-') {
                       isHold = true;
                    } else {
                        const interval = parseInt(intervalStr, 10);
                        if (!isNaN(interval) && interval !== 0) {
                            const targetIndex = rootNoteIndexInPalette + (interval - (interval > 0 ? 1 : 0));
                            if (targetIndex >= 0 && targetIndex < scalePalette.length) {
                                let baseNote = scalePalette[targetIndex];
                                let targetMidi = baseNote.midi + (track.octaveOffset * 12);
                                noteToPlay = { midi: Math.max(0, Math.min(127, targetMidi)) };
                            }
                        }
                    }
                    
                    if (isHold && noteEvents.length > 0) {
                       const lastEvent = noteEvents[noteEvents.length - 1];
                       if(lastEvent.type === 'off') {
                            const onEvent = noteEvents.find(e => e.type === 'on' && e.note === lastEvent.note && e.tick < lastEvent.tick);
                            if(onEvent) {
                                lastEvent.tick += beatDurationTicks;
                            }
                       }
                    } else if(noteToPlay) {
                        let humanizedTick = currentTimeTicks;
                        if(isHumanizerActive) {
                            const timeOffsetRatio = (timingVariation / 100) * (Math.random() * 2 - 1);
                            humanizedTick += Math.round(beatDurationTicks * timeOffsetRatio);
                        }
                         let humanizedVelocity = track.baseVelocity;
                        if(isHumanizerActive) {
                            const velOffset = Math.floor(velocityVariation * (Math.random() * 2 - 1) * (127/50));
                            humanizedVelocity += velOffset;
                        }
                        humanizedVelocity = Math.max(1, Math.min(127, Math.round(humanizedVelocity)));

                        noteEvents.push({ type: 'on', tick: humanizedTick, note: noteToPlay.midi, velocity: humanizedVelocity, channel: track.channel });
                        noteEvents.push({ type: 'off', tick: humanizedTick + beatDurationTicks, note: noteToPlay.midi, channel: track.channel });
                    }
                    currentTimeTicks += beatDurationTicks;
                });
            });
            
            if (noteEvents.length > 0) {
                midiTracks.push(noteEvents);
            }
        });

        if (midiTracks.length === 0) {
            alert("No notes to export.");
            return;
        }

        const writeStringToBytes = (str) => Array.from(str).map(c => c.charCodeAt(0));
        const write32 = (n) => [(n >> 24) & 0xFF, (n >> 16) & 0xFF, (n >> 8) & 0xFF, n & 0xFF];
        const write16 = (n) => [(n >> 8) & 0xFF, n & 0xFF];
        
        const writeVariableLength = (n) => {
            let buf = [n & 0x7F];
            n >>= 7;
            while (n > 0) {
                buf.unshift((n & 0x7F) | 0x80);
                n >>= 7;
            }
            return buf;
        };

        const header = [
            ...writeStringToBytes('MThd'),
            ...write32(6),
            ...write16(1),
            ...write16(midiTracks.length),
            ...write16(ticksPerBeat)
        ];

        let allTrackBytes = [];
        midiTracks.forEach((events) => {
            events.sort((a, b) => a.tick - b.tick);
            let trackBytes = [];
            let lastTick = 0;
            events.forEach(event => {
                const delta = event.tick - lastTick;
                trackBytes.push(...writeVariableLength(delta));
                let status = (event.type === 'on' ? 0x90 : 0x80) | event.channel;
                trackBytes.push(status, event.note, event.velocity || 0);
                lastTick = event.tick;
            });
            
            trackBytes.push(...writeVariableLength(0));
            trackBytes.push(0xFF, 0x2F, 0x00);
            
            const trackHeader = [
                ...writeStringToBytes('MTrk'),
                ...write32(trackBytes.length)
            ];
            allTrackBytes.push(...trackHeader, ...trackBytes);
        });
        
        const midiBytes = new Uint8Array([...header, ...allTrackBytes]);
        const blob = new Blob([midiBytes], { type: 'audio/midi' });
        
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'piano_song.mid';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    // --- PUBLIC API ---
    window.SongMakerSystem = {
        init: function(dependencies) {
            deps = { ...deps, ...dependencies };
            setupSongMakerControls();
        },
        stop: function(resetButtonUI = true) {
            stopSongMaker(resetButtonUI);
        },
        isPlaying: function() {
            return isSongMakerPlaying;
        }
    };

})();